site_name: 物理学知识自学指南和笔记
site_author: foxhunter
theme:
  name: material
repo_url: https://github.com/forxhunter/PhysicsDIY/
edit_url: https://github.com/forxhunter/tree/main/edit/
nav:
  - 前言: 'index.md'
  - 复杂系统: 
    - 'Phase Transition & Renormalization Group': 'ComplexSystems/PTRG.md'
    - '非线性动力学和混沌' : "ComplexSystems/NonlinearDynamics.md"
  - 科研进度:
    - '图灵斑图' : "Research/Notes_for_PatterFormation.md"
  - 网站搭建:
    - 'GitPages' : "WebBuilt/GitPages.md"